import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function StudentDashboard({ studentData, attendanceStatus, handRaised, files, sessionEnded, onRaiseHand, onLowerHand, }) {
    if (sessionEnded) {
        return (_jsx("div", { className: "min-h-screen bg-zinc-950 flex items-center justify-center", children: _jsxs("div", { className: "bg-zinc-900 border border-zinc-800 rounded-2xl p-10 text-center", children: [_jsx("p", { className: "text-white font-semibold text-lg", children: "Class Ended" }), _jsx("p", { className: "text-zinc-500 text-sm mt-2", children: "The teacher has ended the session." })] }) }));
    }
    return (_jsx("div", { className: "min-h-screen bg-zinc-950 p-6", children: _jsxs("div", { className: "max-w-2xl mx-auto flex flex-col gap-5", children: [_jsxs("div", { className: "bg-zinc-900 border border-zinc-800 rounded-xl p-4 flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("p", { className: "text-white font-semibold", children: studentData.name }), _jsxs("p", { className: "text-zinc-500 text-xs mt-0.5", children: [studentData.rollNumber, " \u00B7 Session: ", studentData.sessionCode] })] }), attendanceStatus && (_jsx("span", { className: `text-xs px-3 py-1 rounded-full font-medium ${attendanceStatus === "present"
                                ? "bg-emerald-500/10 text-emerald-400"
                                : "bg-yellow-500/10 text-yellow-400"}`, children: attendanceStatus === "present" ? "Present" : "Late" }))] }), _jsxs("div", { className: "bg-zinc-900 border border-zinc-800 rounded-xl p-5 flex flex-col items-center gap-4", children: [_jsx("p", { className: "text-zinc-400 text-sm", children: "Have a question?" }), _jsx("button", { onClick: handRaised ? onLowerHand : onRaiseHand, className: `w-full py-4 rounded-xl font-semibold text-lg transition-all ${handRaised
                                ? "bg-yellow-500/20 border border-yellow-500/40 text-yellow-400"
                                : "bg-emerald-600 hover:bg-emerald-700 text-white"}`, children: handRaised ? "✋ Hand Raised — Click to Lower" : "Raise Hand" })] }), _jsxs("div", { className: "bg-zinc-900 border border-zinc-800 rounded-xl p-5", children: [_jsxs("h2", { className: "text-white font-semibold mb-4", children: ["Shared Files", files.length > 0 && (_jsxs("span", { className: "ml-2 text-zinc-500 text-sm font-normal", children: ["(", files.length, ")"] }))] }), files.length === 0 ? (_jsx("p", { className: "text-zinc-600 text-sm text-center py-6", children: "No files shared yet" })) : (_jsx("div", { className: "flex flex-col gap-2", children: files.map((file) => (_jsxs("a", { href: file.fileUrl, target: "_blank", rel: "noopener noreferrer", className: "flex items-center justify-between bg-zinc-800 hover:bg-zinc-700 rounded-lg px-4 py-3 transition-colors", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("span", { className: "text-xs bg-zinc-700 text-zinc-300 px-2 py-0.5 rounded", children: file.category.toUpperCase() }), _jsx("span", { className: "text-white text-sm", children: file.originalName })] }), _jsxs("span", { className: "text-zinc-500 text-xs", children: [(file.sizeBytes / 1024).toFixed(1), " KB"] })] }, file.fileId))) }))] })] }) }));
}
